# Generated by Django 4.2.23 on 2025-08-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitem',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='processing', max_length=20),
        ),
    ]
