# Generated by Django 4.2.23 on 2025-08-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_remove_message_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expertise_areas',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='help_requests_fulfilled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='helper_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_available_to_help',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_local_expert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages_spoken',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='travel_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='travel_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='travel_status',
            field=models.CharField(choices=[('traveling', 'Currently Traveling'), ('resident', 'Local Resident'), ('expat', 'Living Abroad Long-term'), ('returning', 'Returning Home')], default='resident', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='years_in_current_location',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
