<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-09-18 13:31
=======
# Generated by Django 4.2.23 on 2025-09-22 11:08
>>>>>>> fb8be1c487c40f3b76bb40e8403faf9146d682fb

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_travel_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyitem',
            name='status',
            field=models.CharField(default='pending_upload', max_length=20),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
