# api/urls.py

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import RegistrationAPIView, ProfileViewSet, FriendRequestViewSet, CommunityViewSet, StoryPostViewSet
from .messaging_views import (
    ConversationViewSet, MessageViewSet, UserEncryptionKeyViewSet, PublicKeyAPIView
)
from .discovery_views import DiscoveryViewSet, TravelStatusViewSet

# A router automatically generates the URLs for a ViewSet
router = DefaultRouter()
# 'profiles' will be the base name for the generated URLs (e.g., /api/profiles/, /api/profiles/1/)
router.register(r'profiles', ProfileViewSet, basename='profile')
router.register(r'friend-requests', FriendRequestViewSet, basename='friend-request')
router.register(r'communities', CommunityViewSet, basename='community')
router.register(r'stories', StoryPostViewSet, basename='story')

# Messaging endpoints
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')
router.register(r'encryption-keys', UserEncryptionKeyViewSet, basename='encryption-key')

# Discovery and Travel endpoints (NEW - Core app features)
router.register(r'discover', DiscoveryViewSet, basename='discover')
router.register(r'travel-status', TravelStatusViewSet, basename='travel-status')

urlpatterns = [
    # Path for user registration
    path('auth/register/', RegistrationAPIView.as_view(), name='register'),
    
    # Public key endpoint for encryption
    path('public-keys/', PublicKeyAPIView.as_view(), name='public-keys'),
    
    # Include all the URLs generated by the router
    path('', include(router.urls)),
]